//All customers
# GET http://localhost:3000/api/customers

###

//Register custumer
POST http://localhost:3000/api/customers/register
Content-Type: application/json

{
 "username": "Hanna" ,
 "password": "123",
 "email": "hanna@test.com"
}
###

//Login customer 
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
 "username": "Hanna" ,
 "password": "123"
}
###



//Get all products
GET http://localhost:3000/api/products
###